basePath: /api/v1
definitions:
  models.Category:
    properties:
      created_at:
        type: string
      id:
        type: integer
      is_default:
        type: boolean
      name:
        maxLength: 100
        minLength: 2
        type: string
      type:
        enum:
        - expense
        - income
        type: string
      updated_at:
        type: string
    required:
    - name
    - type
    type: object
  models.CategoryRequest:
    properties:
      name:
        maxLength: 100
        minLength: 2
        type: string
      type:
        enum:
        - expense
        - income
        type: string
    required:
    - name
    - type
    type: object
  models.DeleteCategoryResponse:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      id:
        type: integer
      is_default:
        type: boolean
      name:
        maxLength: 100
        minLength: 2
        type: string
      type:
        enum:
        - expense
        - income
        type: string
      updated_at:
        type: string
    required:
    - name
    - type
    type: object
  models.Expense:
    properties:
      amount:
        type: number
      category:
        allOf:
        - $ref: '#/definitions/models.Category'
        description: RELATIONSHIPS
      created_at:
        type: string
      deleted_at:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
    type: object
  models.ExpenseRequest:
    properties:
      amount:
        type: number
      category_id:
        type: integer
      name:
        type: string
    required:
    - amount
    - name
    type: object
  models.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  models.LoginResponse:
    properties:
      token:
        type: string
    type: object
  models.RegisterRequest:
    properties:
      email:
        type: string
      name:
        maxLength: 100
        minLength: 2
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - name
    - password
    type: object
  models.RegisterResponse:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/models.UserResponse'
    type: object
  models.UserResponse:
    properties:
      categories:
        description: RELATIONSHIPS
        items:
          $ref: '#/definitions/models.Category'
        type: array
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  utils.PaginationResponse-array_models_Category:
    properties:
      data:
        items:
          $ref: '#/definitions/models.Category'
        type: array
      limit:
        type: integer
      page:
        type: integer
      total:
        type: integer
      total_pages:
        type: integer
    type: object
  utils.Response-any:
    properties:
      data: {}
      error:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
  utils.Response-array_models_Expense:
    properties:
      data:
        items:
          $ref: '#/definitions/models.Expense'
        type: array
      error:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
  utils.Response-models_Category:
    properties:
      data:
        $ref: '#/definitions/models.Category'
      error:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
  utils.Response-models_DeleteCategoryResponse:
    properties:
      data:
        $ref: '#/definitions/models.DeleteCategoryResponse'
      error:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
  utils.Response-models_Expense:
    properties:
      data:
        $ref: '#/definitions/models.Expense'
      error:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
  utils.Response-models_LoginResponse:
    properties:
      data:
        $ref: '#/definitions/models.LoginResponse'
      error:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
  utils.Response-models_RegisterResponse:
    properties:
      data:
        $ref: '#/definitions/models.RegisterResponse'
      error:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
  utils.Response-models_UserResponse:
    properties:
      data:
        $ref: '#/definitions/models.UserResponse'
      error:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
  utils.ResponseWithPagination-array_models_Category:
    properties:
      data:
        $ref: '#/definitions/utils.PaginationResponse-array_models_Category'
      error:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
host: localhost:8080
info:
  contact:
    email: gonanggoneng@gmail.com
    name: Anang
    url: http://github.com/anangkf
  description: API documentation for Expense Tracker project.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Expense Tracker API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate user
      parameters:
      - description: User authentication data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response-models_LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Response-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Response-any'
      summary: Login users
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Create a new user account
      parameters:
      - description: User registration data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/utils.Response-models_RegisterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Response-any'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/utils.Response-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Response-any'
      summary: Register users
      tags:
      - auth
  /categories:
    get:
      consumes:
      - application/json
      description: Get all categories for the authenticated user
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Number of items per page
        in: query
        name: limit
        type: integer
      - default: id
        description: Sort by field
        in: query
        name: sortBy
        type: string
      - default: asc
        description: Sort order (asc or desc)
        in: query
        name: order
        type: string
      - description: Filter by category name
        in: query
        name: name
        type: string
      - description: Filter by category type
        in: query
        name: type
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseWithPagination-array_models_Category'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.Response-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Response-any'
      security:
      - BearerAuth: []
      summary: Get categories by user ID
      tags:
      - categories
    post:
      consumes:
      - application/json
      description: Create a new category for the authenticated user
      parameters:
      - description: Category data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CategoryRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/utils.Response-models_Category'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Response-any'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.Response-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Response-any'
      security:
      - BearerAuth: []
      summary: Create a new category
      tags:
      - categories
  /categories/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a category for the authenticated user
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response-models_DeleteCategoryResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.Response-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Response-any'
      security:
      - BearerAuth: []
      summary: Delete a category
      tags:
      - categories
    put:
      consumes:
      - application/json
      description: Update a category for the authenticated user
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      - description: Category data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CategoryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response-models_Category'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Response-any'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.Response-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Response-any'
      security:
      - BearerAuth: []
      summary: Update a category
      tags:
      - categories
  /expenses:
    get:
      consumes:
      - application/json
      description: Get all expenses for the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response-array_models_Expense'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.Response-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Response-any'
      security:
      - BearerAuth: []
      summary: Get expenses by user ID
      tags:
      - expenses
    post:
      consumes:
      - application/json
      description: Create a new expense for the authenticated user
      parameters:
      - description: Expense data
        in: body
        name: expense
        required: true
        schema:
          $ref: '#/definitions/models.ExpenseRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/utils.Response-models_Expense'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Response-any'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.Response-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Response-any'
      security:
      - BearerAuth: []
      summary: Create a new expense
      tags:
      - expenses
  /expenses/{id}:
    delete:
      consumes:
      - application/json
      description: Delete an expense for the authenticated user
      parameters:
      - description: Expense ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response-models_Expense'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Response-any'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.Response-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Response-any'
      security:
      - BearerAuth: []
      summary: Delete an expense
      tags:
      - expenses
    get:
      consumes:
      - application/json
      description: Get an expense by ID for the authenticated user
      parameters:
      - description: Expense ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response-models_Expense'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Response-any'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.Response-any'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.Response-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Response-any'
      security:
      - BearerAuth: []
      summary: Get an expense by ID
      tags:
      - expenses
    put:
      consumes:
      - application/json
      description: Update an expense for the authenticated user
      parameters:
      - description: Expense ID
        in: path
        name: id
        required: true
        type: integer
      - description: Expense data
        in: body
        name: expense
        required: true
        schema:
          $ref: '#/definitions/models.ExpenseRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response-models_Expense'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Response-any'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.Response-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Response-any'
      security:
      - BearerAuth: []
      summary: Update an expense
      tags:
      - expenses
  /user/profile:
    get:
      consumes:
      - application/json
      description: Get the profile of the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response-models_UserResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.Response-any'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.Response-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Response-any'
      security:
      - BearerAuth: []
      summary: Get user profile
      tags:
      - users
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
